[package]
name = "llm-fetcher"
edition = "2021"
version = "0.1.1"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.91"
form_urlencoded = "1.2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasi = "0.13.3"
wit-bindgen = {version= "0.34.0"}
